### ISSUE TITLE
Turn off AllenNLP's parameter value logging

### ISSUE THREAD

**Issue by sleepinyourhat** [nyu-mll/jiant#658]
AllenNLP dumps a bunch of redundant parameter values to the log by default, and we can't easily access the code that would disable this. Either:
– Find a way to pass AllenNLP a decoy log.
– Patch AllenNLP to turn off verbose logging.

Sub-issue of #602

**Comment by pruksmhc** [comment]
Did some preliminary research into this, seems relevant
https://github.com/allenai/allennlp/issues/2506

**Comment by pruksmhc** [comment]
Addressed with https://github.com/nyu-mll/jiant/commit/7be8fdb9b8b24296b559bf307d7cacbe9a669b33

**Comment by sleepinyourhat** [comment]
I'm still seeing a bunch of relevant-looking logs junk: 

06/24 04:03:12 PM: Number of trainable parameters: 334649361
06/24 04:03:12 PM: Converting Params object to dict; logging of default values will not occur when dictionary parameters are used subsequently.
06/24 04:03:12 PM: CURRENTLY DEFINED PARAMETERS: 
06/24 04:03:12 PM: lr = 2e-05
06/24 04:03:12 PM: t_total = 29500
06/24 04:03:12 PM: warmup = 0.1
06/24 04:03:12 PM: type = reduce_on_plateau
06/24 04:03:12 PM: Converting Params object to dict; logging of default values will not occur when dictionary parameters are used subsequently.
06/24 04:03:12 PM: CURRENTLY DEFINED PARAMETERS: 
06/24 04:03:12 PM: mode = max
06/24 04:03:12 PM: factor = 0.5
06/24 04:03:12 PM: patience = 4
06/24 04:03:12 PM: threshold = 0.0001
06/24 04:03:12 PM: threshold_mode = abs
06/24 04:03:12 PM: verbose = True
06/24 04:03:12 PM: type = bert_adam
06/24 04:03:12 PM: parameter_groups = None
06/24 04:03:12 PM: Number of trainable parameters: 334649361
06/24 04:03:12 PM: Converting Params object to dict; logging of default values will not occur when dictionary parameters are used subsequently.
06/24 04:03:12 PM: CURRENTLY DEFINED PARAMETERS: 
06/24 04:03:12 PM: lr = 2e-05
06/24 04:03:12 PM: t_total = 29500
06/24 04:03:12 PM: warmup = 0.1
06/24 04:03:12 PM: type = reduce_on_plateau
06/24 04:03:12 PM: Converting Params object to dict; logging of default values will not occur when dictionary parameters are used subsequently.
06/24 04:03:12 PM: CURRENTLY DEFINED PARAMETERS: 
06/24 04:03:12 PM: mode = max
06/24 04:03:12 PM: factor = 0.5
06/24 04:03:12 PM: patience = 4
06/24 04:03:12 PM: threshold = 0.0001
06/24 04:03:12 PM: threshold_mode = abs
06/24 04:03:12 PM: verbose = True
06/24 04:03:12 PM: Starting training without restoring from a checkpoint.

**Comment by sleepinyourhat** [comment]
The other log issue seems mostly fixed, but this one is mainly about the stuff coming from Allen.

**Comment by pruksmhc** [comment]
Update - this seems to be coming from the Optimizer class from Allennlp - will ping a PR to their side.

**Comment by sleepinyourhat** [comment]
Sounds good. We can drop the needed_for_1.0 label if there's no easy way to suppress it.

**Comment by pruksmhc** [comment]
Yeah, this is more a patch to Allennlp so dropping the label.

**Comment by pyeres** [comment]
If you're ready to lose the logged info, an easy way to do this w/o touching AllenNLP would be to increase (and then restore) the log level around [this code](https://github.com/nyu-mll/jiant/blob/master/jiant/trainer.py#L510-L513) from `INFO` to `WARNING`, like this:

```
        log_level = log.getLogger().level
        log.getLogger().setLevel(log.WARNING)
        self._optimizer = Optimizer.from_params(train_params, optimizer_params)
        self._scheduler = LearningRateScheduler.from_params(
            self._optimizer, copy.deepcopy(scheduler_params)
        )
        log.getLogger().setLevel(log_level)
```

**Comment by sleepinyourhat** [comment]
This would me an excellent 10m PR if anyone has 10m!
